url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Alcaldía Rio Chico" # the name of your site, e.g. ACME Corp.
email: webmaster@alcaldiariochico.com.ve

# Author
author: Laymont Arratia
author_email: laymont@gmail.com
author_website: laymont.github.io

# Social links
twitter_username:
github_username:
facebook_username:
instagram_username:
youtube_username:
tiktok_username:


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      description: ""
      author: "Prensa Municipio Páez"
      categories: []
      tags: []
      seo_title: ""

# Pagination
paginate: 3
per_page: 3
paginate_path: "blog/page/:num/"

jekyll_admin:
  homepage: "post"
  hidden_links:
    - pages
    - staticfiles
    #- datafiles
    - configuration

plugins:
  - jekyll-paginate
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

postcss:
  cache: false