url: "https://alcaldiariochico.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "alcaldiariochico.github.io" # the subpath of your site, e.g. /blog
title: "Alcaldía Rio Chico" # the name of your site, e.g. ACME Corp.
email: webmaster@alcaldiariochico.com.ve
timezone: America/Caracas

# Author
author: Laymont Arratia
author_email: laymont@gmail.com
author_website: laymont.github.io

# Social links

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      description: ""
      author: "Prensa Municipio Páez"
      categories: []
      tags: []
      seo_title: ""

# Pagination
paginate: 3
per_page: 3
paginate_path: "blog/page/:num/"

jekyll_admin:
  homepage: "post"
  hidden_links:
    - pages
    - staticfiles
    #- datafiles
    - configuration

plugins:
  - jekyll-paginate
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Handling Reading
safe                : false
include             : [".htaccess", "node_modules/tailwindcss"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false


postcss:
  cache: false